name: Workflow1
on:
  workflow_dispatch:
    inputs:
      workflow2_name:
        description: 'Workflow2 Name for Triggering'
        required: true
        default: 'Workflow2'
jobs:
  build:
      permissions: write-all
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: test
          run: |
            mkdir folder

        - name: build
          run: docker build . --file Dockerfile --tag ghcr.io/maxxam123/testtest:latest
 
        - name: Build the Docker image
          run: echo "${{secrets.GITHUB_TOKEN}}" | docker login https://ghcr.io -u ${{github.actor}} --password-stdin

        - name: test
          run: |
            IMAGE_ID=ghcr.io/${{github.repository_owner}}/testtest:${{github.run_id}}
            docker push ghcr.io/maxxam123/testtest:latest
